# Generated by Django 4.2.13 on 2024-07-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ImageField(default='blog/profile/profile.jpg', upload_to='blog/profile/'),
        ),
    ]
